### ISSUE TITLE
Error: Cookies can only be modified in a Server Action or Route Handler.

### ISSUE THREAD

**Issue by phpgng** [moshest/next-client-cookies#19]
I try to set cookies inside "use server". But I got Error: Cookies can only be modified in a Server Action or Route Handler.

**Comment by moshest** [comment]
This is not the purpose of this library. 

This library build to solve the issue of SSR when some client components can't access the cookies because they are pre-rendered on the server. 

Please refer to the README, client components that rendered on the server are NOT equal to `server-side` components.
